### ISSUE TITLE
Project Review 2 Criteria Checklist

### ISSUE THREAD

**Issue by Matmorcat** [UNCG-CSE/Poststorm_Imagery#136]
For the October 31st presentation, some items need to be completed by each member on the [progress report](https://github.com/UNCG-CSE/Poststorm_Imagery/blob/project-reqs/docs/reports/progress_report_31-10-2019.md) in the `project-reqs` branch. Don't worry about pushing to beta or master until everything is pretty much ready on it!

*You can check off things in your section below once you've completed them*

## Rinty

- [x] Work done towards the tasks with links to notebooks, documents, etc.
- [x] Number of hours spent on each task.
- [x] Description of the results obtained from the tasks. (4-5 lines for each task)

## Daniel

- [ ] Work done towards the tasks with links to notebooks, documents, etc.
- [x] Number of hours spent on each task.
- [x] Description of the results obtained from the tasks. (4-5 lines for each task)

## Matt

- [x] Work done towards the tasks with links to notebooks, documents, etc.
- [x] Number of hours spent on each task.
- [x] Description of the results obtained from the tasks. (4-5 lines for each task)

## Nafis

- [x] Work done towards the tasks with links to notebooks, documents, etc.
- [x] Number of hours spent on each task.
- [x] Description of the results obtained from the tasks. (4-5 lines for each task)

## John

- [x] Work done towards the tasks with links to notebooks, documents, etc.
- [x] Number of hours spent on each task.
- [x] Description of the results obtained from the tasks. (4-5 lines for each task)

**Comment by ShahNafisRafique** [comment]
IM NOT NAFIS

**Comment by Matmorcat** [comment]
This has been completed.
