### ISSUE TITLE
Node server todo list

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-CSE/Poststorm_Imagery#88]
## Server side

- [x] Programmatically determine IP/protocol for get/post requests both server and client side
- [x] Programmatically retrieve Auth0 bearer token
- [x] Server config file

## Client/React side
- [x] Restructure the way logout/login groups of links are shown

- [x] Maybe have a YAML file for page titles

## Documentation

- [x] Comments

- [x] dashboard v2.md

**Comment by ShahNafisRafique** [comment]
done
